networks:
  bridge-network:
    driver: bridge

services:
  python:
    build:
      dockerfile: Dockerfile
    container_name: python-counter
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - 8000:8000
    networks:
      - bridge-network
    depends_on:
      postgres:
        condition: service_healthy
    command: ./run

  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: "tracker"
      POSTGRES_USER: "voldemar"
      POSTGRES_PASSWORD: "voldemar"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - bridge-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
