"""'init'

Revision ID: 95c99131bf0c
Revises: 
Create Date: 2022-11-13 19:14:14.687973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95c99131bf0c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_dt', sa.DateTime(), nullable=False),
    sa.Column('user_agent', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('request_info')
    # ### end Alembic commands ###
